language: ruby
sudo: false
rvm:
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/actionview_4_1.gemfile
  - gemfiles/actionview_4_2.gemfile
  - gemfiles/actionview_5_0.gemfile
  - gemfiles/actionview_5_1.gemfile
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/actionview_4_1.gemfile
branches:
  only:
    - master
before_install:
  - gem update --system --no-doc
